apiVersion: v1
kind: Service
metadata:
 name: monimus-node
 labels:
   name: monimus-node
spec:
 type: LoadBalancer
 ports:
   - port: 5000
     targetPort: 5000
     protocol: TCP
 selector:
   name: monimus-node
